
<?php
$scopeConfig = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\App\Config\ScopeConfigInterface::class);
// Example: Fetching a specific config value
 $access_token = $scopeConfig->getValue('matrixinsta_section/matrixinsta_group/matrixinsta_accesstoken', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
  

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://graph.instagram.com/me/media?fields=id%2Ccaption%20%2Cthumbnail_url%20%2Cmedia_type%2Cmedia_url%2Cpermalink&access_token='.$access_token.'&limit=10',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'GET',
));

$response = curl_exec($curl);

curl_close($curl);
//echo $response;
$posts = json_decode($response, true);
// Display posts
if (!empty($posts['data'] ) ) {
    ?>
    <section class="seenTheGramWrapper">
        <div class="container">
          <h3>As seen on the Gram</h3>
        </div>
        <div class="masonryWrapper">
          <div class="grid">
            <?php foreach ($posts['data'] as $post) { ?>
            <div class="grid-item">
                <?php if ($post['media_type'] === 'IMAGE' || $post['media_type'] === 'CAROUSEL_ALBUM') { 
                    echo "<a href='{$post['permalink']}' target='_blank'><img src='{$post['media_url']}'/></a>";
                    } elseif ($post['media_type'] === 'VIDEO') {
                   echo "<a href='{$post['permalink']}' target='_blank'><img src='{$post['thumbnail_url']}'  /></a>";
                    }
                    ?>
              
            </div> 
            <?php } ?> 
          </div>
        </div>
    </section>

    <script type="text/javascript">
require(['jquery', 'imagesloaded', 'masonry'], function($, imagesLoaded, Masonry) {   
    $(document).ready(function() {
        var $grid = $(".grid");
        imagesLoaded($grid, function() {
            new Masonry($grid[0], {  // Correct way to initialize Masonry
                itemSelector: ".grid-item"
            });
        });
    });
});
</script>
    
<?php } ?>
